### ISSUE TITLE
Unable to validate null fields with min or max rules

### ISSUE THREAD

**Issue by ferrao** [jfstn/Validator#20]
```
Validator.make({test: null}, {test: 'required'}).fails();
Validator.make({test: null}, {test: 'max:1'}).fails();
Validator.make({test: null}, {test: 'min:1'}).fails();
````

The first validation runs just fine, but the last two blow up with:
```
TypeError: Cannot read property 'length' of null
    at i.value (/Users/ferrao/Dev/Workspace/academia-codigo/noire/noire-admissions/node_modules/Validator/dist/Validator.js:1:11858)
    at i.value (/Users/ferrao/Dev/Workspace/academia-codigo/noire/noire-admissions/node_modules/Validator/dist/Validator.js:1:11722)
    at i.value (/Users/ferrao/Dev/Workspace/academia-codigo/noire/noire-admissions/node_modules/Validator/dist/Validator.js:1:7346)
    at /Users/ferrao/Dev/Workspace/academia-codigo/noire/noire-admissions/node_modules/Validator/dist/Validator.js:1:5983
    at Array.forEach (<anonymous>)
    at /Users/ferrao/Dev/Workspace/academia-codigo/noire/noire-admissions/node_modules/Validator/dist/Validator.js:1:5961
    at Array.forEach (<anonymous>)
    at i.value (/Users/ferrao/Dev/Workspace/academia-codigo/noire/noire-admissions/node_modules/Validator/dist/Validator.js:1:5820)
    at i.value (/Users/ferrao/Dev/Workspace/academia-codigo/noire/noire-admissions/node_modules/Validator/dist/Validator.js:1:6077)
```

**Comment by ferrao** [comment]
Thanks @jfstn !
